info:
  title: Default module
  description: ''
  version: 1.0.0
tags: []
paths:
  /api/v1/register:
    post:
      summary: User Registration
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Content-Type
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: name
          in: formData
          type: string
        - name: email
          in: formData
          type: string
        - name: password
          in: formData
          type: string
        - name: password_confirmation
          in: formData
          type: string
      responses:
        '200':
          description: ''
          examples:
            application/json:
              token: 8|tM0QKeg49VLhlUSdHpzIJipEfIQeEcdPI1LEsNYea19c98af
              role: customer
              user:
                id: 5
                name: John Doe
                email: john.doe@example.com
                role: customer
          schema:
            type: object
            properties: {}
      security: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
  /api/v1/login:
    post:
      summary: User Login
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Content-Type
          in: header
          description: ''
          required: false
          type: string
          x-example: application/javascript
        - name: email
          in: formData
          type: string
        - name: password
          in: formData
          type: string
      responses:
        '200':
          description: ''
          headers: {}
          examples:
            application/json:
              token: 30|aS00QV2fhPUGwUF21YhWxz8zMyigq5vGU75Pd4usaa7bba80
              role: admin
              user:
                id: 1
                name: Admin User
                email: admin@example.com
                role: admin
              permissions:
                - admin-dashboard-access
          schema:
            type: object
            properties: {}
      security: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
  /api/v1/logout:
    post:
      summary: User Logout
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: false
          type: string
          x-example: Bearer 28|c1pevwGvITSidJBsC5Xj0E8LreKUwDGcM0iRjtMT9699a1ce
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
      responses:
        '200':
          description: ''
          headers: {}
          examples:
            application/json:
              message: Unauthenticated.
          schema:
            type: object
            properties: {}
      security: []
      produces:
        - application/json
  /api/v1/authorize:
    post:
      summary: Access Authorization
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Content-Type
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Authorization
          in: header
          description: ''
          required: false
          type: string
          x-example: Bearer 18|TDvzav5ivmMOPmWczB8F6k5axyJlTa3NgRPOz2tc70001b18
        - required: true
          name: body
          in: body
          schema:
            type: object
            properties: {}
      responses:
        '200':
          description: ''
          headers: {}
          examples:
            application/json:
              data:
                isAuthorized: true
              message: User authenticated with required permission
          schema:
            type: object
            properties: {}
      security: []
      consumes:
        - application/json
      produces:
        - application/json
  /api/v1/user-permissions:
    get:
      summary: User Permissions
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Authorization
          in: header
          description: ''
          required: false
          type: string
          x-example: Bearer 29|4Iuqql6gWFn28tSaGOBaJ1FgeHqo0DO77VENDNgtb4f7c781
      responses:
        '200':
          description: ''
          headers: {}
          examples:
            application/json:
              data:
                - id: 12
                  slug: admin-dashboard-access
                  description: Access to admin dashboard
                  created_at: '2025-12-30T10:31:30.000000Z'
                  updated_at: '2025-12-30T10:31:30.000000Z'
                  pivot:
                    role_id: 1
                    permission_id: 12
              links:
                first: http://127.0.0.1/api/v1/user-permissions?page=1
                last: http://127.0.0.1/api/v1/user-permissions?page=1
                prev: null
                next: null
                self: http://127.0.0.1/api/v1/user-permissions?page=1
              meta:
                current_page: 1
                from: 1
                to: 1
                per_page: 15
                total: 1
                last_page: 1
                path: http://127.0.0.1/api/v1/user-permissions
              message: Permissions retrieved successfully
          schema:
            type: object
            properties: {}
      security: []
      produces:
        - application/json
  /api/v1/roles:
    get:
      summary: Fetch Roles - Paginated
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: per_page
          in: query
          description: ''
          required: false
          type: integer
          x-example: 10
        - name: page
          in: query
          description: ''
          required: false
          type: integer
          x-example: 1
        - name: search
          in: query
          description: ''
          required: false
          type: string
          x-example: a
        - name: sort_by
          in: query
          description: ''
          required: false
          type: string
          x-example: name
        - name: sort_order
          in: query
          description: ''
          required: false
          type: string
          x-example: desc
        - name: Authorization
          in: header
          description: ''
          required: false
          type: string
          x-example: Bearer 39|2gc5nLJNwEZUu1CLIa3URFEV3p6Mj5JNei612UHO66633832
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Content-Type
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
      responses:
        '200':
          description: ''
          headers: {}
          examples:
            application/json:
              data:
                - id: 2
                  name: agent
                  created_at: '2025-12-29T19:48:29.000000Z'
                  updated_at: '2025-12-29T19:48:29.000000Z'
                - id: 1
                  name: admin
                  created_at: '2025-12-29T19:48:29.000000Z'
                  updated_at: '2025-12-29T19:48:29.000000Z'
              links:
                first: http://127.0.0.1/api/v1/roles?page=1
                last: http://127.0.0.1/api/v1/roles?page=1
                prev: null
                next: null
                self: http://127.0.0.1/api/v1/roles?page=1
              meta:
                current_page: 1
                from: 1
                to: 2
                per_page: 10
                total: 2
                last_page: 1
                path: http://127.0.0.1/api/v1/roles
              message: Roles retrieved successfully
          schema:
            type: object
            properties: {}
      security: []
      produces:
        - application/json
  /api/v1/permissions:
    get:
      summary: Fetch Permissions - Paginated
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: per_page
          in: query
          description: ''
          required: false
          type: integer
          x-example: 10
        - name: page
          in: query
          description: ''
          required: false
          type: integer
          x-example: 1
        - name: search
          in: query
          description: ''
          required: false
          type: string
          x-example: a
        - name: sort_by
          in: query
          description: ''
          required: false
          type: string
          x-example: slug
        - name: sort_order
          in: query
          description: ''
          required: false
          type: string
          x-example: desc
        - name: Authorization
          in: header
          description: ''
          required: false
          type: string
          x-example: Bearer 39|2gc5nLJNwEZUu1CLIa3URFEV3p6Mj5JNei612UHO66633832
        - name: Accept
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
        - name: Content-Type
          in: header
          description: ''
          required: false
          type: string
          x-example: application/json
      responses:
        '200':
          description: ''
          headers: {}
          examples:
            application/json:
              data:
                - id: 11
                  slug: update-permission
                  description: Assign or revoke permission to role
                  created_at: '2025-12-30T10:31:30.000000Z'
                  updated_at: '2025-12-30T10:31:30.000000Z'
                - id: 13
                  slug: customer-dashboard-access
                  description: Access to customer dashboard
                  created_at: '2025-12-30T10:31:30.000000Z'
                  updated_at: '2025-12-30T10:31:30.000000Z'
                - id: 12
                  slug: admin-dashboard-access
                  description: Access to admin dashboard
                  created_at: '2025-12-30T10:31:30.000000Z'
                  updated_at: '2025-12-30T10:31:30.000000Z'
                - id: 2
                  slug: add-role
                  description: Add a new role
                  created_at: '2025-12-30T10:31:30.000000Z'
                  updated_at: '2025-12-30T10:31:30.000000Z'
                - id: 7
                  slug: add-permission
                  description: Add a new permission
                  created_at: '2025-12-30T10:31:30.000000Z'
                  updated_at: '2025-12-30T10:31:30.000000Z'
              links:
                first: http://127.0.0.1/api/v1/permissions?page=1
                last: http://127.0.0.1/api/v1/permissions?page=1
                prev: null
                next: null
                self: http://127.0.0.1/api/v1/permissions?page=1
              meta:
                current_page: 1
                from: 1
                to: 5
                per_page: 10
                total: 5
                last_page: 1
                path: http://127.0.0.1/api/v1/permissions
              message: Permissions retrieved successfully
          schema:
            type: object
            properties: {}
      security: []
      produces:
        - application/json
security: []
swagger: '2.0'
definitions: {}
securityDefinitions: {}
x-components:
  responses: {}
