apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  labels:
    app: bookmyshow
    tier: frontend
spec:
  type: NodePort
  selector:
    app: bookmyshow
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Access via http://localhost:30080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
